name: clusterlogs
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=4.11.0
  - conda-package-handling=1.6.1
  - dash=1.19.0
  - dash-bootstrap-components=0.13.1
  - dash-extensions=0.0.71
  - flask=2.0.3
  - intel-openmp=2019.4
  - jinja2=3.0.3
  - nltk=3.5
  - pandas=1.1.3
  - pip=20.0.2
  - plotly=5.6.0
  - python=3.8.3
  - setuptools=47.1.1
  - six=1.15.0
  - spacy=3.2.2
  - tqdm=4.46.0
  - urllib3=1.25.8
  - wheel=0.34.2
  - yaml=0.1.7
  - pip:
    - editdistance==0.6.0
    - git+https://github.com/boudinfl/pke.git
    - hdbscan==0.8.28
    - kneed==0.7.0
    - matplotlib==3.3.2
    - pyonmttok==1.30.1
    - pytextrank==3.2.2
    - python-rake==1.5.0
    - rake-nltk==1.0.6
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - yake==0.4.3
